version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=xarala_bootcamp
      - JWT_SECRET=your-super-secret-key
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_SECRET=your-refresh-secret
      - PORT=3000
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=xarala_bootcamp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 