services:
  - type: web
    name: xarala-bootcamp-api
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: xarala-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: xarala-postgres
    databaseName: xarala_bootcamp
    user: xarala_user
    plan: starter 